Fix build issue on MSYS2 and Cygwin
The is* macros on MSYS2 (native) and Cygwin are implemented as table
lookups and expect values representable as 'unsigned char'. Passing a
signed char can lead to negative array indices and compile-time
errors (-Werror=char-subscripts).

Add explicit casts to 'unsigned char' to all affected is* calls, as
recommended by the ISALPHA(3) manual page.

Example error message on Cygwin:

../src/helper/log.c: In function ‘find_nonprint_char’:
../src/helper/log.c:525:33: error: array subscript has type ‘char’ [-Werror=char-subscripts]
  525 |                 if (!isprint(buf[i]))

Change-Id: I9c7a5cc1085e15fed0f3f974ec943abad44e68a0
Signed-off-by: Marc Schink <dev@zapb.de>
Reviewed-on: https://review.openocd.org/c/openocd/+/9478
Tested-by: jenkins
Reviewed-by: Antonio Borneo <borneo.antonio@gmail.com>