flash/aducm302x: Fix error message with gcc 14.2.0
This fixes:

	src/flash/nor/aducm302x.c: In function 'aducm302x_flash_bank_command':
	src/flash/nor/aducm302x.c:633:40: error: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
	  633 |         aducm302x_info = calloc(sizeof(struct aducm302x_flash_bank), 1);
	      |                                        ^~~~~~
	src/flash/nor/aducm302x.c:633:40: note: earlier argument should specify number of elements, later size of each element
	src/flash/nor/aducm302x.c: In function 'aducm4x50_flash_bank_command':
	src/flash/nor/aducm302x.c:660:40: error: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
	  660 |         aducm302x_info = calloc(sizeof(struct aducm302x_flash_bank), 1);
	      |                                        ^~~~~~
	src/flash/nor/aducm302x.c:660:40: note: earlier argument should specify number of elements, later size of each element

Fixes: b41618254f1b ("Added VSCode directory to gitignore. Bumped submodule with USB MUX tweak. Removed #if 1. adiv5_swd_dp_ops is still referenced so include the source file in the build but do not register it as a transport and do not use transport_is_swd from v5. Two identical files that set up transport SWD. Use the latest. Avoid warning about function pointer not being set for Flash Programmer. Add flash programmer for ADuCM302x and ADuCM4050.")
Signed-off-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>