ice1000: Fix error message with gcc 14.2.0
This fixes:

src/jtag/drivers/ice1000.c: In function 'ice1000_swd_queue_cmd':
src/jtag/drivers/ice1000.c:2186:32: error: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
 2186 |         packet = calloc(sizeof(struct swd_packet), 1);
      |                                ^~~~~~

Fixes: 8fbcce61e63c ("initial swd support added back")
Signed-off-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>